preprocessing:
  random_state: 10
  test_size: 0.2
  raw_path: ../data/raw/data_reviews.csv
  train_path: ../data/processed/train_data.csv
  test_path: ../data/processed/test_data.csv
  scrape_path: ../data/raw/scrape_data.csv
  connection_path: ../config/connection.json
train:
  max_length: 512
  random_state: 10
  learning_rate: 2.0e-05
  tokenizer_path: cointegrated/rubert-tiny2
  model_path: cointegrated/rubert-tiny2
  trainer_path: ../models/history
  trainer_log_path: ../models/history/history.json
  epochs: 5
  weight_decay: 0.01
  per_device_batch_size: 64
  batch_size_split: 10
  metrics_path: ../report/metrics/metrics.json
test:
  model_path: ../models/bert-tiny2
  evaluate_path: ../data/check/test_data.csv
endpoints:
#  exploratory: 'http://localhost:8000/compute_eda'
#  train: 'http://localhost:8000/train'
#  prediction_input: 'http://localhost:8000/predict_from_input'
#  prediction_from_file: 'http://localhost:8000/predict'
#  scrape: 'http://localhost:8000/scrape'
  exploratory: 'http://fastapi:8000/compute_eda'
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_from_input'
  prediction_from_file: 'http://fastapi:8000/predict'
  scrape: 'http://fastapi:8000/scrape'
